# Generated by Django 2.2.3 on 2019-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
