# Generated by Django 2.2.3 on 2019-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_business_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
