# Generated by Django 2.2.3 on 2019-08-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='html_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='html_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
