# Generated by Django 2.2.3 on 2019-08-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190804_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='logo_file_path',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='display_in_navbar',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('profile_picture_file', models.CharField(max_length=255)),
                ('testimonial', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Business')),
            ],
        ),
    ]
